services:
  - type: web
    name: skyline-bot
    runtime: python
    buildCommand: sudo apt-get install -y ffmpeg libopus0 libopus-dev && pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
